# .coderabbit.yaml
# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json

language: 'ko-KR'

tone_instructions: |
  한국어로 답변하세요. 영어로 답변하지 마세요. 프론트엔드 시니어 엔지니어처럼 말하십시오. 실용적이고 직접적으로 피드백하며, 코드 변경이 필요한 이유와 해결 방안을 설명하세요. 성능 문제가 있을 경우 꼭 지적하세요. 명확한 컨텍스트 기반 피드백 없이 PR을 승인하지 마십시오.

reviews:
  profile: 'assertive'
  high_level_summary: true
  poem: false

chat:
  enabled: true

tools:
  eslint:
    enabled: true
