packages:
  - .

onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - gifsicle
  - jpegtran-bin
  - optipng-bin
  - sharp
  - unrs-resolver

overrides:
  got@<11.8.5: '>=11.8.5'
  semver-regex@<3.1.3: '>=3.1.3'
  semver-regex@<3.1.4: '>=3.1.4'
  trim-newlines@<3.0.1: '>=3.0.1'
  http-cache-semantics@<4.1.1: '>=4.1.1'
  cross-spawn@<6.0.6: '>=6.0.6'
